README.md
I made few changes in README while I was reading it. I believe that code snippets highlighting improves the readability.
=> Readme improvements and typo

README.md, slips.py
The same problem with CPU utilisation affects also `master` branch. This set of commits fixes the main issue, simplifies the input reading and finally, out of topic, change of my reference in the contributor list.
=> The set of commits refering to the busy waiting issue #16

modules/lstm-cc-detection-1/lstm-cc-detection-1.py
Added tuple id in  the evidence text
=> Add tuple ID to the alert text

.gitignore, README.md
I got the Slips working on my localhost using conda, as there's no note about conda in the readme, I put it there.
=> Add note about conda to the readme

modules/flowalerts/flowalert.py
=> flowalert. Fix datetime again. It was wrong before for some reason

modules/UpdateManager/update_file_manager.py
=> Fix remote TI files failed to update.

modules/flowalerts/set_evidence.py, modules/threat_intelligence/threat_intelligence.py, slips_files/core/database/_profile_flow.py, slips_files/core/database/database.py, slips_files/core/evidenceProcess.py, slips_files/core/inputProcess.py, slips_files/core/profilerProcess.py
=> Fix suplicate alerts in suricata files (processing the same line over and over)

install.sh
=> directory path correction

docs/installation.md
fixed typo in StratosphereLinuxIPS/docs/installation.md line 91 apt-get -y installtshark... => apt-get -y install tshark
=> fixed typo in StratosphereLinuxIPS/docs/installation.md

CHANGELOG.md, docs/detection_modules.md, modules/http_analyzer/http_analyzer.py
issue #246 :
Added evidence 'set_evidence_http_traffic' in line 387 and called it inside run at line 568
=>  Add an alert when there's a new HTTP flow #246

requirements.txt, slips.py
#267 used termcolor instead or hardcoding ascii color code
=> added termcolor to slips.py

.github/workflows/CI-production-testing.yml, .github/workflows/CI-publishing.yml
Issue: #274 
Changes: Updated the workflows to test SLIPS for macos and release the image for macos as mentioned in the issue.
=> Updated workflows to test and publish macos image

modules/CESNET/CESNET.py, modules/RiskIQ/RiskIQ.py, modules/arp/arp.py, modules/blocking/blocking.py, modules/ensembling/ensembling.py, modules/exporting_alerts/exporting_alerts.py, modules/flowalerts/flowalerts.py, modules/flowmldetection/flowmldetection.py, modules/http_analyzer/http_analyzer.py, modules/ip_info/ip_info.py, modules/leak_detector/leak_detector.py, modules/network_discovery/network_discovery.py, modules/rnn-cc-detection/rnn-cc-detection.py, modules/template/template.py, modules/threat_intelligence/threat_intelligence.py, modules/timeline/timeline.py, modules/virustotal/virustotal.py, slips_files/common/abstracts.py, slips_files/core/logsProcess.py
=> Update slips abstract Module

docs/detection_modules.md
Updated stratoletters graph link in docs/detection_modules.md
The Stratoletters graph link was coming from my branch, it was not showing since I deleted respective branch , changed the link to show from Stratosphere develop branch
=> stratoletters image link update

docs/installation.md
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.
=> typo in installation page of docs, corrected filename of dataset file

docs/installation.md
Closes #463 
Fixed the code for displaying the image.
=> Updated installation.md to fix the image display

docs/installation.md
Merge of the doc PR done to master before. So develop has this change too. Mistake by merging to master first the PR.
=> Sebas merge documentation PR from master

slips_files/core/database/redis_db/alert_handler.py
There was a small typo in the alert_handler.py code, which may have led to unexpected behavior. This pull request fixes that typo error.
=> fixed small typo in alert_handler.py

modules/progress_bar/progress_bar.py, slips_files/common/slips_utils.py, slips_files/core/output.py
=> progress_bar: handle non printable chars

.github/workflows/CI-production-testing.yml, .github/workflows/CI-staging.yml, tests/test_dns.py
=> added test for dns.py

.github/workflows/CI-production-testing.yml, .github/workflows/CI-staging.yml, dataset/test16-malicious-zeek-dir/arp.log, dataset/test9-mixed-zeek-dir/arp.log, modules/flowalerts/notice.py, modules/flowalerts/ssl.py, modules/progress_bar/progress_bar.py, slips_files/common/slips_utils.py, slips_files/core/output.py, tests/integration_tests/test_zeek_dataset.py, tests/test_dns.py, tests/test_notice.py
=> added  test_notice.py

.github/workflows/CI-production-testing.yml, .github/workflows/CI-staging.yml, tests/test_software.py
=> added test_software.py

.github/workflows/CI-production-testing.yml, .github/workflows/CI-staging.yml, tests/test_smtp.py
=> Created test_smtp.py

.github/workflows/CI-production-testing.yml, .github/workflows/CI-staging.yml, tests/test_ssl.py
added test for ssl in flowalerts module
=> added test ssl in flowalerts module

.github/workflows/CI-production-testing.yml, .github/workflows/CI-staging.yml, tests/test_ssh.py
added test for ssh.py in flowalerts module
=> added test for ssh.py in flowalerts module

docs/installation.md
=> Fix typo install

.github/workflows/CI-production-testing.yml, .github/workflows/CI-staging.yml, docs/detection_modules.md, modules/flowalerts/conn.py, modules/network_discovery/horizontal_portscan.py, modules/update_manager/update_manager.py, tests/module_factory.py, tests/test_downloaded_file.py, tests/test_network_discovery.py, tests/test_smtp.py, tests/test_ssh.py, tests/test_ssl.py, tests/test_update_file_manager.py
=> added test_network_discovery.py

managers/process_manager.py, modules/flowalerts/ssl.py, slips_files/common/abstracts/core.py, slips_files/common/abstracts/flowalerts_analyzer.py, slips_files/common/abstracts/module.py, slips_files/core/evidencehandler.py
=> Give modules more time to process msgs

.github/workflows/CI-production-testing.yml, .github/workflows/CI-staging.yml, .pre-commit-config.yaml, slips/main.py, tests/test_main.py
=> added unittest for main

.github/workflows/CI-production-testing.yml, .github/workflows/CI-staging.yml, slips_files/core/input.py, tests/module_factory.py, tests/test_arp.py, tests/test_inputProc.py, tests/test_output.py
=> added some more test for arp

slips_files/common/abstracts/async_module.py
fixes [#1015](https://github.com/stratosphereips/StratosphereLinuxIPS/issues/1015)
=> Fix unable to get the main event loop when starting flowalerts

managers/process_manager.py, slips_files/core/input.py, tests/module_factory.py
fixes [#1021](https://github.com/stratosphereips/StratosphereLinuxIPS/issues/1021)
=> fix race condition preventing the input and profiler semaphores to be acquired 

docs/features.md, docs/flowalerts.md, modules/flowalerts/set_evidence.py, modules/flowalerts/ssl.py, modules/ip_info/ip_info.py, slips_files/common/slips_utils.py, slips_files/core/structures/evidence.py, tests/test_ip_info.py, tests/test_ssl.py
=> Detect ssl certificate hostname mismatch

.github/pull_request_template.md, .github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml, modules/flowalerts/conn.py, pytest.ini, slips_files/core/database/database_manager.py, slips_files/core/database/redis_db/database.py, tests/test_conn.py, tests/test_slips_utils.py
=> Fix FP conn without dns

docs/usage.md, managers/process_manager.py, slips_files/core/helpers/whitelist/domain_whitelist.py, slips_files/core/helpers/whitelist/matcher.py, slips_files/core/profiler.py
Closes [#1201](https://github.com/stratosphereips/StratosphereLinuxIPS/issues/1201)
=> Fix not reading all given flows due to whitelisting all flows and evidence to tranco domains 

managers/process_manager.py, managers/ui_manager.py, slips_files/core/database/database_manager.py, slips_files/core/database/redis_db/database.py, slips_files/core/database/sqlite_db/database.py, slips_files/core/input.py, slips_files/core/output.py, webinterface/database/database.py
=> Fix clearing zeek files from the database when the web interface is started using -w

modules/flowalerts/conn.py, modules/flowalerts/dns.py, slips_files/common/slips_utils.py, slips_files/core/database/database_manager.py, slips_files/core/database/redis_db/database.py, slips_files/core/database/redis_db/profile_handler.py, tests/integration_tests/test_pcap_dataset.py, tests/test_profile_handler.py
closes #1232, #1211, #1210 and #1209
=> Fix "device changing IPs", "Invalid DNS answers" and "different localnet connection" FPs 

.github/workflows/unit-tests.yml, config/slips.yaml, docs/features.md, docs/flowalerts.md, modules/flowalerts/conn.py, modules/flowalerts/dns.py, modules/flowalerts/set_evidence.py, modules/flowalerts/tunnel.py, modules/flowmldetection/flowmldetection.py, modules/update_manager/update_manager.py, slips_files/common/parsers/config_parser.py, slips_files/core/structures/evidence.py, tests/test_dns.py, tests/test_set_evidence.py, tests/test_tunnel.py
=> Add a detection for GRE scans and change the threat level of gre tunnel detections

slips_files/core/database/redis_db/database.py, slips_files/core/database/sqlite_db/database.py, slips_files/core/profiler.py
=> Fix sqlite cannot rollback

modules/ip_info/ip_info.py
=> ip_info: fix problem getting domain registrant

managers/process_manager.py, slips_files/common/abstracts/module.py, slips_files/core/database/database_manager.py, slips_files/core/database/sqlite_db/database.py
=> Fix SQLite db is locked 

managers/process_manager.py, modules/flowalerts/flowalerts.py, modules/ip_info/ip_info.py, modules/update_manager/update_manager.py, slips_files/common/abstracts/iasync_module.py, slips_files/core/database/redis_db/alert_handler.py
=> Remove cpu intensive dead code
